export const CREATE_FILE_REQUEST = "CREATE_FILE_REQUEST";
export const CREATE_FILE_SUCCESS = "CREATE_FILE_SUCCESS";
export const CREATE_FILE_FAILED = "CREATE_FILE_FAILED";

export const FORWARD_REQUEST_REQUEST = "FORWARD_REQUEST_REQUEST";
export const FORWARD_REQUEST_SUCCESS = "FORWARD_REQUEST_SUCCESS";
export const FORWARD_REQUEST_FAILED = "FORWARD_REQUEST_FAILED";