export const UPLOAD_FILE_REQUEST = "UPLOAD_FILE_REQUEST";
export const UPLOAD_FILE_SUCCESS = "UPLOAD_FILE_SUCCESS";
export const UPLOAD_FILE_FAILED = "UPLOAD_FILE_FAILED";

export const GET_UPLOAD_URL_REQUEST = "GET_UPLOAD_URL_REQUEST";
export const GET_UPLOAD_URL_SUCCESS = "GET_UPLOAD_URL_SUCCESS";
export const GET_UPLOAD_URL_FAILED = "GET_UPLOAD_URL_FAILED";
